config/routes.rb
Rails.application.routes.draw do


#Url::Application.routes.draw do
  get '/:id(/:desc)' => 'shorts#show', :as => 'short'
  get '/' => 'shorts#new', :as => 'new_short'
  post '/' => 'shorts#create', :as => 'shorts'
end

app/models/short.rb
class Short < ActiveRecord::Base


  attr_accessor :desc
 



  def b36_id
    self.id.to_i.to_s(36)
  end

 def to_param
    if self.desc.nil?
     b36_id
   else
    "#{b36_id}/#{self.desc.parameterize}"
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController
  # GET /shorts/1



  def show
    @short = Short.find(params[:id].to_i(36))

    respond_to do |format|
      format.html { redirect_to @short.long }
    end
  end

  def new
    @short = Short.new

    respond_to do |format|
      format.html 
    end
  end

  # POST /shorts
  def create

    @short = Short.new params.permit![:short]

    respond_to do |format|
     if @short.save
       format.html { render action: "show" } 
       else
       format.html { render action: "new" }
    end
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorts_helper.rb
module ShortsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Url</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shorts/_form.html.erb
<%= form_for(@short) do |f| %>
  <% if @short.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short.errors.count, "error") %> prohibited this short from being saved:</h2>

      <ul>
      <% @short.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Put it here, we'll shorten-it" %><br />
    <%= f.text_field :long %>
  </div>

  <div class="actions">
    <%= f.submit "shorten-it" %>
  </div>
<% end %>

app/views/shorts/edit.html.erb
<h1>Edit - it</h1>

<%= render 'form' %>

<%= link_to 'Show', @short %> |
<%= link_to 'Back', shorts_path %>

app/views/shorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shorts</h1>

<table>
  <thead>
    <tr>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shorts.each do |short| %>
      <tr>
        <td><%= short.long %></td>
        <td><%= link_to 'Show', short %></td>
        <td><%= link_to 'Edit', edit_short_path(short) %></td>
        <td><%= link_to 'Destroy', short, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Short', new_short_path %>

app/views/shorts/new.html.erb
<h1>Shorten-it</h1>

<%= render 'form' %>

app/views/shorts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>We shortened-it </h3>

<p>This is your shortened link :) Use it! <%= link_to short_url(@short), short_url(@short) %></p>

<p> Unshortened Link <%= link_to @short.long, @short.long %></p>

<p><%= link_to 'Use shorten-it again', new_short_path %></p> 